services:
  mongo:
    image: mongo:7
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  localstack:
    image: localstack/localstack:3
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./infra/localstack/init.sh:/etc/localstack/init/ready.d/init.sh
      - localstack-data:/var/lib/localstack

volumes:
  mongo-data:
  localstack-data:
